export const urls = {
    indentityAccountLogin: '/Identity/Account/Login',
    indentityAccountRegister: '/Identity/Account/Register',
    articles: '/Articles',
    articlesCreate: '/Articles/Create',
    articlesEdit: '/Articles/Edit/',
    articlesDelete: '/Articles/Delete/',
    articlesDetails: '/Articles/Details/',
    articlesDetailsView: '/Articles/DetailsView/',
    subscriptions: '/Subscriptions',
    subscriptionsCreate: '/Subscriptions/Create',
    subscriptionsEdit: '/Subscriptions/Edit/',
    subscriptionsDelete: '/Subscriptions/Delete/',
    subscriptionsDetails: '/Subscriptions/Details/',
    subscriptionsSelectSubsrciptionDuration: '/Subscriptions/SelectSubscriptionDuration/',
    subscriptionsConfirmPayment: '/Subscriptions/ConfirmPayment/',
    subscriptionsPaymentSuccess: '/Subscriptions/PaymentSuccess/',
    subscriptionsUserSubscriptions: '/Subscriptions/UserSubscriptions',
    users: '/Users',
    usersCreate: '/Users/Create',
    usersEdit: '/Users/Edit/',
    usersDelete: '/Users/Delete/',
    usersDetails: '/Users/Details/',
};